/**
 * Zones of the M5 vertical slice (10.1, 10.2, spec 16 M5.1): the Chess Academy, its town Rookhaven,
 * Knight’s Way (route 1, with a First Blood challenge zone, 10.4) and Thistle Meadow (a wild patch).
 * Maps are Tiled JSON files in `maps/` (generated by `tools/gen-maps.ts`); encounter tables and
 * rates are PLAYTEST values (R-WORLD-002) tuned against the 17.2 / 10.2 pacing target, see
 * `progression.ts` (PACING, sessionEncounters).
 *
 * Warps: Academy doormat <-> Rookhaven door; Rookhaven north gate <-> Knight’s Way south end;
 * Knight’s Way north end <-> Thistle Meadow south end.
 */
import type { TiledMap, ZoneDef } from './types.ts';
import academyHall from './maps/academy_hall.json' with { type: 'json' };
import academyTown from './maps/academy_town.json' with { type: 'json' };
import route1 from './maps/route_1.json' with { type: 'json' };
import thistleMeadow from './maps/thistle_meadow.json' with { type: 'json' };

const isObj = (v: unknown): v is Record<string, unknown> => typeof v === 'object' && v !== null;

/**
 * A validated boundary for imported Tiled JSON: checks the fields the game reads so the rest of the
 * code can use the typed `TiledMap` (parseZone checks the contents in depth).
 */
export function asTiledMap(json: unknown, name: string): TiledMap {
  const bad = (why: string) => new Error(`map ${name}: ${why}`);
  if (!isObj(json)) throw bad('not an object');
  if (json.type !== 'map' || json.orientation !== 'orthogonal') throw bad('not an orthogonal map');
  if (json.tilewidth !== 16 || json.tileheight !== 16) throw bad('tiles must be 16x16');
  if (json.infinite !== false) throw bad('infinite maps are not supported');
  if (!Number.isInteger(json.width) || !Number.isInteger(json.height)) throw bad('bad size');
  if (!Array.isArray(json.layers) || !Array.isArray(json.tilesets)) throw bad('missing layers');
  for (const l of json.layers as unknown[]) {
    if (!isObj(l) || typeof l.name !== 'string') throw bad('bad layer');
    if (l.type === 'tilelayer') {
      if (!Array.isArray(l.data) || !(l.data as unknown[]).every((n) => Number.isInteger(n)))
        throw bad(`layer ${l.name} needs uncompressed CSV-style data`);
    } else if (l.type === 'objectgroup') {
      if (!Array.isArray(l.objects)) throw bad(`layer ${l.name} has no objects`);
    } else throw bad(`unsupported layer type ${String(l.type)}`);
  }
  for (const t of json.tilesets as unknown[]) {
    if (!isObj(t) || !Number.isInteger(t.firstgid) || !Number.isInteger(t.tilecount))
      throw bad('tilesets must be embedded (firstgid, tilecount, tiles)');
  }
  return json as TiledMap;
}

export const ZONES: readonly ZoneDef[] = [
  {
    id: 'academy_hall',
    name: 'Chess Academy',
    kind: 'interior',
    map: asTiledMap(academyHall, 'academy_hall'),
    encounterRate: 0,
    encounterGrace: 0,
    encounters: [],
    format: 'first_blood',
  },
  {
    id: 'academy_town',
    name: 'Rookhaven',
    kind: 'town',
    map: asTiledMap(academyTown, 'academy_town'),
    encounterRate: 0,
    encounterGrace: 0,
    encounters: [],
    format: 'first_blood',
  },
  {
    id: 'route_1',
    name: 'Knight’s Way',
    kind: 'route',
    map: asTiledMap(route1, 'route_1'),
    // PLAYTEST (R-WORLD-002): about one encounter per 20 steps in the grass (6 safe + 1/0.07).
    encounterRate: 0.07,
    encounterGrace: 6,
    encounters: [
      { weight: 40, levels: [1, 3], element: 'tide', name: 'Wild Bubblet' },
      { weight: 30, levels: [1, 3], element: 'ember', name: 'Wild Flickerlet' },
      { weight: 30, levels: [2, 3], element: 'grove', name: 'Wild Sproutlet' },
    ],
    format: 'first_blood',
  },
  {
    id: 'thistle_meadow',
    name: 'Thistle Meadow',
    kind: 'wild',
    map: asTiledMap(thistleMeadow, 'thistle_meadow'),
    // PLAYTEST: a denser patch for players who come to fight (about one per 12 grass steps).
    encounterRate: 0.12,
    encounterGrace: 4,
    encounters: [
      { weight: 30, levels: [2, 5], element: 'grove', name: 'Wild Mosslope' },
      { weight: 25, levels: [2, 5], element: 'ember', name: 'Wild Blazelope' },
      { weight: 25, levels: [2, 5], element: 'tide', name: 'Wild Surflope' },
      { weight: 20, levels: [3, 6], name: 'Wild Wanderer' },
    ],
    format: 'first_blood',
  },
];

export const START_ZONE = 'academy_hall';
