/**
 * `pnpm content:index` — regenerates packages/content/registry.generated.ts from the module files
 * (13.5). CI regenerates it and fails if the committed file differs.
 */
import { readdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('../../../../', import.meta.url).pathname;
const CONTENT = join(ROOT, 'packages/content');
const KINDS = ['abilities', 'items', 'traits'] as const;
const PREFIX: Record<(typeof KINDS)[number], string> = {
  abilities: 'ability',
  items: 'item',
  traits: 'trait',
};

export function moduleIds(kind: (typeof KINDS)[number]): string[] {
  return readdirSync(join(CONTENT, kind))
    .filter((f) => f.endsWith('.ts') && !f.endsWith('.test.ts'))
    .map((f) => f.slice(0, -3))
    .sort();
}

export function generate(): string {
  const lines: string[] = [
    '// GENERATED by `pnpm content:index` — do not edit. CI fails if this file is stale (13.5).',
    "import type { AbilityDef, ItemDef, TraitDef } from '@chain-theorem/rules/sdk';",
  ];
  const lists: Record<string, string[]> = {};
  for (const kind of KINDS) {
    lists[kind] = [];
    for (const id of moduleIds(kind)) {
      const name = `${PREFIX[kind]}_${id}`;
      lines.push(`import ${name} from './${kind}/${id}.ts';`);
      lists[kind]?.push(name);
    }
  }
  lines.push('');
  lines.push(
    `export const abilities: readonly AbilityDef[] = [${(lists.abilities ?? []).join(', ')}];`,
  );
  lines.push(`export const items: readonly ItemDef[] = [${(lists.items ?? []).join(', ')}];`);
  lines.push(`export const traits: readonly TraitDef[] = [${(lists.traits ?? []).join(', ')}];`);
  lines.push('');
  return lines.join('\n');
}

if (process.argv[1]?.endsWith('index-gen.ts')) {
  const out = join(CONTENT, 'registry.generated.ts');
  const text = generate();
  const before = existsSync(out) ? readFileSync(out, 'utf8') : '';
  writeFileSync(out, text);
  const counts = KINDS.map((k) => `${moduleIds(k).length} ${k}`).join(', ');
  console.log(`content:index ${before === text ? 'unchanged' : 'written'}: ${counts}`);
}
